name: Create Random LeetCode Issue

on:
  schedule:
    - cron: "0 21 * * 5" # 매주 금요일 오후 9시 UTC = 한국 토요일 오전 6시
  workflow_dispatch:  # 수동 실행도 가능

jobs:
  create-issue:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Fetch random LeetCode problem
      run: python fetch_random_problem.py

    - name: Commit and push updated solved IDs
      run: |
        if [ "${{ github.actor }}" == "github-actions[bot]" ]; then
            git config --global user.name "GitHub Actions"
            git config --global user.email "github-actions[bot]@users.noreply.github.com"
        else
            git config --global user.name "${{ github.actor }}"
            git config --global user.email "${{ github.actor }}@users.noreply.github.com"
        fi
        git add solved_ids.json
        git commit -m "Update solved problem IDs"
        git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:${{ github.ref }}

    - name: Read issue data
      id: read-issue
      run: |
        ISSUE=$(cat issue.json)
        TITLE=$(echo $ISSUE | jq -r '.title')
        BODY=$(echo $ISSUE | jq -r '.body')
        echo "title=$TITLE" >> $GITHUB_OUTPUT
        echo "body=$BODY" >> $GITHUB_OUTPUT

    - name: Create Issue Action
      uses: dacbd/create-issue-action@main
      with:
        token: ${{secrets.GITHUB_TOKEN}}
        title: ${{ steps.read-issue.outputs.title }}
        assignees: ${{github.actor}}
        body: ${{ steps.read-issue.outputs.body }}
